name: mta_com
description: MTA.COM Travel Agency App
version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design:
  generate: true
  assets:
    - assets/images/
